-- Generated by Drizzle. Coordination tables and the issue generation column
-- are already installed by migrations 0212 and 0213; only hire DDL is new.
CREATE TABLE "agent_hire_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"idempotency_key" text NOT NULL,
	"request_fingerprint" text NOT NULL,
	"agent_id" uuid,
	"approval_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agent_hire_requests" ADD CONSTRAINT "agent_hire_requests_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "agent_hire_requests_company_key_unique_idx" ON "agent_hire_requests" USING btree ("company_id","idempotency_key");
